<?php
/*
 * Template Name: Content with Map VueJS SPA
 * Description: A Page Template with a VueJs APP loader.
 */

 get_header();
?>

<?php
// Start the Loop.
while ( have_posts() ) :
	the_post();
    // Regular page print
    get_template_part( 'partials/content', 'page' );
    // Custom page template print
    echo '<h3>VueJS Map !</h3>';

	?>
	<div class="wrap">
		<div id="primary" class="content-area">
			<main id="main" class="site-main" role="main">
				<div id="wp-vue-app">
					This text will be replaced by the Vue App when the SPA build (generated by Webpack) is enqueued in WordPress.
				</div><!-- #vue-app -->
			</main><!-- #main -->
		</div><!-- #primary -->
	</div><!-- .wrap -->
	<?php

	// If comments are open or we have at least one comment, load up the comment template.
	if ( comments_open() || get_comments_number() ) {
		comments_template();
	}

endwhile;

get_footer();
